ci: Pass tests under macOS
pure-fish/pure pull request #340
Opened 2024-01-13 19:49 UTC by hyperupcall

**Related**: Fixes #294

## Description

This fixes the tests so macOS CI passes. There were too main issues:
- [osx tr printing unexpected spaces](https://stackoverflow.com/questions/30927590/wc-on-osx-return-includes-spaces)
- `set -U` not working on macOS (currently fish version 3.7)
  - to fix this, erasing the variable before setting it somehow made it work

## First contribution?

Check the [:+1: Contribute][contribute] section and the [contributing guide][contributing].

### Documentation

#### Usage

```shell
❯ set --universal pure_enable_feature_foo true
```

## Acceptance Checks

* [ ] documentation is up-to-date:
  * [ ] [features list][features] ;
  * [ ] [Prompt Symbol][symbol] ;
  * [ ] [🔌 Features' Flags][feature-flag] ;
* [ ] feature flag is present in `conf.d/pure.fish` ;
* [ ] symbol is present in `conf.d/pure.fish` ;
* [x] tests are passing (I can help you :hugs: ):
  * [ ] config are tested (cf. [tests/_pure.test.fish][config-test]) ;
  * [ ] feature is covered ;
* [ ] customization is available ;
* [x] feature is implemented.

[config-test]: tests/_pure.test.fish
[contribute]: /pure-fish/pure/#1-contribute
[contributing]: CONTRIBUTING.md
[feature-flag]: /pure-fish/pure/#-features-flags
[symbol]: /pure-fish/pure/#prompt-symbol
[features]: /pure-fish/pure/#features

2024-01-16 09:23 UTC, edouard-lopez commented on .github/workflows/ci.yml
> +        run: brew install fish
Could you create a matrix to test several versions or at least specify the version to install so we know what version we test again?

2024-01-16 10:25 UTC, edouard-lopez commented on tests/_pure_is_inside_container.test.fish
> +end)
Please use a dedicated test instead: 

```fish
if test (uname -s) != Darwin
	cleanup_spy
	@test "_pure_is_inside_container: true for Github Action on Ubuntu" (
	    set --universal pure_enable_container_detection true
	
	    _pure_is_inside_container
	) $status -eq $SUCCESS
	end
end

if test (uname -s) = Darwin
	cleanup_spy
	@test "_pure_is_inside_container: false for Github Action on MacOS" (
	    set --universal pure_enable_container_detection true
	
	    _pure_is_inside_container
	) $status -eq $FAILURE
	end
end
```

2024-01-24 03:59 UTC, hyperupcall commented
@edouard-lopez I've updated the tests to use a dedicated container test for macOS and Linux, but I don't think it's possible to specify a particular version of Fish to install with Homebrew. Usually, only the latest versions are supported. Some applications like postgres do have multiple versions and some applications do have custom taps with multiple versions, but that does not seem to be the case for Fish. Maybe that could be fixed by someone a follow-up PR?

2024-01-24 09:30 UTC, edouard-lopez requested changes
I introduced a regression with the code I suggested that added an extra `end` on each block. Could you update and then rebase on master ?

2024-01-24 09:30 UTC, edouard-lopez commented on tests/_pure_is_inside_container.test.fish
> +    end
I introduce an extraneous `end` that causes the [tests to fail](https://github.com/pure-fish/pure/actions/runs/7635299204/job/20807724766?pr=340#step:5:104)
```suggestion
```

2024-01-24 09:30 UTC, edouard-lopez commented on tests/_pure_is_inside_container.test.fish
> +    end
Same here
```suggestion
```

2024-02-16 10:50 UTC, edouard-lopez commented
There is an issue with `not ok 97 _pure_is_inside_container: true for Github Action on Ubuntu`. I will have a look

2024-02-16 15:06 UTC, edouard-lopez commented
The failure was due to error in the test file (not cleaning a mocked method), I will fix in #347

2024-02-16 15:06 UTC, merged